@startuml
start
:Студент нажимает "Переменные";
while (Есть ещё переменные?) is (да)
  :Система пишет символ переменной;
  if (Известно значение переменной?) then (да)
    :Система пишет значение переменной;
    :Система добавляет кнопку "Заменить";
  else (нет)
    :Система пишет все ограничения 
    переменной, начиная с множества чисел;
  endif
endwhile (нет)
:Система добавляет кнопку "Создать переменную";
:Система показывает окно;
stop
@enduml