@startuml
start
:Студент перетаскивает выражение 
в поле "Ответ" (создаётся копия);
:Система сравнивает выражение 
с эталонным ответом;

if (Выражение совпадает с эталоном?) then (да)
  :Показать "Правильно!";
  :Задача считается решённой;
  stop
else (нет)
  :Показать "Неправильно!";
  :Очистить поле "Ответ";
  stop
endif
@enduml