@startuml
start
:Студент нажимает "Создать переменную";

repeat :Студент вводит символ;
repeat while (Символ занят?) is (да)

repeat
  :Студент вводит выражение;
  :Система проверяет синтаксис выражения;
  if (Синтаксис ошибочен?) then (да)
    :Ошибка синтаксиса;
  else (нет)
    if (Выражение содержит переменные?) then (да)
      :Система проверяет переменные 
      в выражении на существование;
      if (Есть несуществующие переменные?) then (да)
        :Ошибка: необъявленные переменные;
      else (нет)
        :Система проверяет корректность 
        использования переменных;
        if (Есть нарушения ограничений?) then (да)
          :Ошибка: нарушены ограничения переменных;
        else (нет)
        endif
      endif
    else (нет)
    endif
  endif
repeat while (Были ошибки?) is (да)

:Сохранить переменную с выражением;
:Обновить список переменных;
:Показать сообщение об успехе;
stop
@enduml