@startuml
start
:Студент хочет редактировать выражение;
while (Выражение можно преобразовывать?) is (да)
  :Студент выделяет подвыражение;
  if (Выбран один узел?) then (да)
    if (Это оператор?) then (да)
      :Система просматривает подвыражение
      созданое им и его операндами;
      :Система выводит список
      доступных сейчас действий для оператора;
    else (нет)
      :Система выводит свойства узла;
    endif
  else (нет)
    
  endif
  :Студент выбирает действие;
endwhile (нельзя)
stop
@enduml